### ISSUE TITLE
Xdebug?

### ISSUE THREAD

**Issue by medj** [sergeyklay/phalcon-compose#10]
Is it possible to provide a guide on how to enable xdebug. It says its included but I don't see any reference to it.

**Comment by sergeyklay** [comment]
Hello @medj
I'll try to sort out ASAP.

**Comment by medj** [comment]
Just to give you an idea of what I tried. In my docker-compose.yml, I added an environment configuration which I saw somewhere on stackoverflow. 

```
services:
  application:
    build: containers/core
    container_name: phalcon.compose.volume
    volumes:
      - ./application:/var/www/phalcon
      - ./cache:/var/cache/phalcon
      - ./logs:/var/log/phalcon
    tty: true
    environment:
        XDEBUG_CONFIG: remote_host=172.18.0.7 remote_port=9002
```

However, after checking my `phpinfo`, the port didn't seem to change.

I guess I still need to brush up on docker-compose. When I `build`, does it take my new settings in this file into account?

Also, if I need to make changes to the php.ini file in the future, what is the correct way to do such a thing?

And lastly, I notice the `public` folder in `application`. Is there a way to change things so that it would use `public_html` instead?

**Comment by sergeyklay** [comment]
@medj I've already found answers to all your questions. I'll release a new major version coming soon.

**Comment by sergeyklay** [comment]
@medj 
I've refactored `docker-compose.yml` so now project use all-in-one image: Apache 2 + PHP 7 + Xdebug + Composer.

Also I updated `README.md`. See `Setting environment variables`.

For enabling Docker integration in PhpStorm refer to:
* https://blog.jetbrains.com/phpstorm/2015/10/docker-support-in-phpstorm/
* https://mhdzaherghaibeh.name/2016/08/27/how-to-configure-phpstorm-to-work-with-native-mac-docker/
* https://gist.github.com/chadrien/c90927ec2d160ffea9c4
* https://youtrack.jetbrains.com/issue/IDEA-153973#comment=27-1484220

Could you please try it now? I've release alpha version.
https://github.com/sergeyklay/phalcon-compose/releases/tag/v2.0.0-alpha.1


**Note:** This is pre-release

**Comment by medj** [comment]
I like this work you've done with the environment variables file.

However, after setting it all up, I still can't get debugger to work. I'll admit that I haven't added the Docker extension to PHPStorm, but I am not sure that is really necessary. Look here: https://gist.github.com/chadrien/c90927ec2d160ffea9c4 (`digitalit` comment bear bottom)

I have the following settings that are being output by `phpinfo()` and in my PHPStorm Configuration.
![screen shot 2016-10-05 at 4 10 27 pm](https://cloud.githubusercontent.com/assets/882534/19129777/878d9fa8-8b16-11e6-9008-91e12440f63b.png)

![screen shot 2016-10-05 at 4 11 10 pm](https://cloud.githubusercontent.com/assets/882534/19129782/8bba55bc-8b16-11e6-8854-209666c539d0.png)

**Comment by medj** [comment]
By the way, my Phalcon project seems to break in this new revision. Get an error with `$this->dispatcher->getModuleName()`.  I'm wondering if it has something to do with the htaccess file I'm using:

```
AddDefaultCharset UTF-8
Options +FollowSymLinks -ExecCGI -Includes -IncludesNOEXEC -Indexes -MultiViews -SymLinksIfOwnerMatch

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]
</IfModule>
```

**Comment by sergeyklay** [comment]
@medj I provided links to integration Docker with PhpStorm to avoid any issues in the future :) Could you provide error message or log? I'm not sure about htaccess.

**Comment by medj** [comment]
I found the root of the problem, but I don't know how to fix it. I eventually do a check within the application to see if a `modules` folder exists.

`if (file_exists($this->getConfig()->getPath('modules'))`

This is failing on this new Docker instance in which it didn't on the old one. Here is the value being passed to `file_exists`.

`/var/www/phalcon/app/modules/`

Apparently this path doesn't exist.

Is it possible I have to alter something in the `variables.env` file?
I notice the following variable:
`WEB_DOCUMENT_ROOT=/project/public`

Not sure what needs to be changed to fix that path problem above.

**Comment by sergeyklay** [comment]
@medj  Good catch! Frankly speaking, I don't see the need for `Application Core Container` so I've dropped it in next alpha release. I moved volumed from `Application Core Container` to the `PHP Container`. Could you please check now? https://github.com/sergeyklay/phalcon-compose/releases/tag/v2.0.0-alpha.3

**Comment by medj** [comment]
@sergeyklay Yes, that seems to have fixed the issue. Thanks!

Just curious, have you ever been able to get debugging working yourself?

**Comment by sergeyklay** [comment]
@medj Could you please try `dev` branch? Note: you have to recreate containers (at least php):
```sh
docker-compose -p my-app up -d --force-recreate
```
I've updated `variables.env.example`. Also check PhpStorm config:

![phpstorm-debug-0](https://cloud.githubusercontent.com/assets/1256298/19173615/3bba33c2-8c31-11e6-9716-93f1f6048a6b.png)


![phpstorm-debug-1](https://cloud.githubusercontent.com/assets/1256298/19173594/00878462-8c31-11e6-8654-0556167647fb.png)

![phpstorm-debug-1 5](https://cloud.githubusercontent.com/assets/1256298/19173595/05129436-8c31-11e6-814d-ce7289567c05.png)

![phpstorm-debug-2](https://cloud.githubusercontent.com/assets/1256298/19173600/0a6084d4-8c31-11e6-8f82-6444f2a8410b.png)

**Comment by sergeyklay** [comment]
![phpstorm-debug-6](https://cloud.githubusercontent.com/assets/1256298/19174011/6f17e5e0-8c34-11e6-9c28-b2199c387398.png)

**Comment by sergeyklay** [comment]
I've amended documentation: https://phalcon-compose.readme.io/docs/docker-container-informations

**Comment by medj** [comment]
Thanks for all of this. However, I'm still not able to debug. I'm going to tell you what I've done.

1. Took your latest version of phalcon-compose.
2. Had to change the `docker-compose.yml` file to listen on port 81 (instead of 80) under php since my 80 is already taken by my local apache server. I also changed mysql to listen on port 3307 (instead of 3306).
3. Ran `docker-compose up` and I was able to view the `phpinfo()` at `http://127.0.0.1:81`
4. My phpinfo file shows the following:
```
SERVER_ADDR	172.20.0.9
REMOTE_ADDR	172.20.0.1
XDEBUG_REMOTE_HOST	172.20.0.9
XDEBUG_REMOTE_PORT	9000
```
5. My PHPStorm has the following configuration:
```
Debug Port: 9000

DBGp Proxy
IDE Key: PHPSTORM
Host: 172.20.0.9
Port: 9000
```
6. Lastly, my `variables.env` file looks like this:
```
# Please provide your host (local machine IP) instead of 192.168.1.129
XDEBUG_REMOTE_HOST=172.20.0.9

# php.ini value for xdebug.remote_port
XDEBUG_REMOTE_PORT=9000

# php.ini value for xdebug.remote_autostart
# XDEBUG_REMOTE_AUTOSTART=1

# php.ini value for xdebug.remote_connect_back
XDEBUG_REMOTE_CONNECT_BACK=0
```

Perhaps given all this information, you can point out my mistake(s).

Thanks!

**Comment by sergeyklay** [comment]
@medj 
Note  you need to provide for Xdebug **your host (local machine IP)**, not Docker ip. Something like `192.168....` not `172.20....`. The same for DBGp .

Then set up the server:
![phpstorm-debug-7](https://cloud.githubusercontent.com/assets/1256298/19180023/37639784-8c6b-11e6-8099-fba3fe04f56f.png)

**Comment by sergeyklay** [comment]
My variables.env file looks like this:
```env
# Debug
# Note: For debugging purposes you have to setup Xdebug by passing required parameters
PHP_DEBUGGER=xdebug

# Please provide your host (local machine IP) instead of 192.168.1.129
XDEBUG_REMOTE_HOST=192.168.1.129

# php.ini value for xdebug.remote_port
XDEBUG_REMOTE_PORT=9000

# php.ini value for xdebug.remote_autostart
# XDEBUG_REMOTE_AUTOSTART=0

# php.ini value for xdebug.remote_connect_back
XDEBUG_REMOTE_CONNECT_BACK=0
```

**Comment by medj** [comment]
Strange, I've configured everything just as you explained, but still can't seem to get it to work.

```
# Debug
# Note: For debugging purposes you have to setup Xdebug by passing required parameters
PHP_DEBUGGER=xdebug

# Please provide your host (local machine IP) instead of 192.168.1.129
XDEBUG_REMOTE_HOST=192.168.0.25

# php.ini value for xdebug.remote_port
XDEBUG_REMOTE_PORT=9000

# php.ini value for xdebug.remote_autostart
# XDEBUG_REMOTE_AUTOSTART=1

# php.ini value for xdebug.remote_connect_back
XDEBUG_REMOTE_CONNECT_BACK=0
```

<img width="274" alt="screen shot 2016-10-07 at 2 40 17 am" src="https://cloud.githubusercontent.com/assets/882534/19180953/a6bd04e6-8c37-11e6-9fbe-6408e0a2a391.png">
<img width="547" alt="screen shot 2016-10-07 at 2 40 48 am" src="https://cloud.githubusercontent.com/assets/882534/19180952/a6ba831a-8c37-11e6-884c-bc6ab417dc03.png">

**Comment by sergeyklay** [comment]
Provide please dubug config: **Run** -> **Edit Configurations...** -> **PHP Web Application**

**Comment by medj** [comment]
<img width="1072" alt="screen shot 2016-10-07 at 10 58 59 am" src="https://cloud.githubusercontent.com/assets/882534/19194842/19d8d01e-8c7d-11e6-8ae7-f179d9ca7ff0.png">

**Comment by sergeyklay** [comment]
@medj So what happens? Could you please explain a bit more? 404 error, notice, nothing, blank screen, etc

**Comment by medj** [comment]
My page loads up, I see the phpinfo().

I've placed a breakpoint on the phpinfo() line and debugging doesn't seem to activate even though I've followed all the steps.

Any further ideas what I may be missing?

**Comment by sergeyklay** [comment]
Well let's again compare all:
![dbg-1](https://cloud.githubusercontent.com/assets/1256298/19198907/20ad3842-8cca-11e6-928b-b9c5e99c805a.png)

![screen shot 2016-10-07 at 8 07 52 pm](https://cloud.githubusercontent.com/assets/1256298/19198909/26d25770-8cca-11e6-8be0-49df417b9d74.png)

![screen shot 2016-10-07 at 8 08 20 pm](https://cloud.githubusercontent.com/assets/1256298/19198914/2b2e9b3a-8cca-11e6-81d4-af6bfc8a357b.png)

![screen shot 2016-10-07 at 8 08 37 pm](https://cloud.githubusercontent.com/assets/1256298/19198917/2e47aaf0-8cca-11e6-9033-bf9260873d2b.png)

![screen shot 2016-10-07 at 8 09 03 pm](https://cloud.githubusercontent.com/assets/1256298/19198920/31424314-8cca-11e6-9b42-393321700de1.png)

**variables.env**:
```
# PostgreSQL
POSTGRES_PASSWORD=
PGDATA=/var/lib/postgresql/data/pgdata

# MySQL
MYSQL_DATABASE=phalcondb
MYSQL_USER=phalcon
MYSQL_PASSWORD=secret
MYSQL_ALLOW_EMPTY_PASSWORD='yes'

# Application
WEB_DOCUMENT_ROOT=/project/public
WEB_ALIAS_DOMAIN=phalcon.local
# production | development | staging | testing
APPLICATION_ENV=development

# Debug
# Note: For debugging purposes you have to setup Xdebug by passing required parameters
PHP_DEBUGGER=xdebug

# Please provide your host (local machine IP) instead of 192.168.1.129
XDEBUG_REMOTE_HOST=192.168.1.129

# php.ini value for xdebug.remote_port
XDEBUG_REMOTE_PORT=9000

# php.ini value for xdebug.remote_autostart
# XDEBUG_REMOTE_AUTOSTART=0

# php.ini value for xdebug.remote_connect_back
XDEBUG_REMOTE_CONNECT_BACK=0

# SSH
CONTAINER=phalcon.compose.php
AUTH_MECHANISM=noAuth
```

```sh
$ ipconfig getifaddr en1
192.168.1.129
```

**Comment by medj** [comment]
```
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' 
192.168.0.25
```

Everything else seems to match exactly. I will tell you though that I may have not set up my Docker plugin correctly within PHPStorm.

One other question:
When you set those environmental values, do the values change for you in the `phpinfo()`?

For example, when I scroll down, I still see:
`xdebug.remote_host` with value `localhost`

Could this be the problem?

**Comment by sergeyklay** [comment]
Before start debug:

![dbg-5](https://cloud.githubusercontent.com/assets/1256298/19211696/44886602-8d4b-11e6-8811-e9e76e268f39.png)

![dbg-4](https://cloud.githubusercontent.com/assets/1256298/19211697/48483592-8d4b-11e6-9655-4d470817f105.png)

![dbg-3](https://cloud.githubusercontent.com/assets/1256298/19211700/4b83ab10-8d4b-11e6-97db-3ba6337326af.png)

![dbg-2](https://cloud.githubusercontent.com/assets/1256298/19211701/4f950244-8d4b-11e6-844b-93f128658c3a.png)

**Comment by sergeyklay** [comment]
@medj Try:
```
docker-compose -p my-app up -d --force-recreate
```

**Comment by sergeyklay** [comment]
@medj Issue is solved?

**Comment by medj** [comment]
@sergeyklay Issue is not solved.
Tried running the command and I still see `localhost` as value. Did you edit your php.ini file at some point?

**Comment by sergeyklay** [comment]
@medj Nope.  Try to reset all containers
```sh
docker-compose -p my-app stop
docker-compose -p my-app rm --force
docker-compose build --no-cache
docker-compose up -d
```


Note: this commands, delete all data, but not your project files in `application/`.

**Comment by sergeyklay** [comment]
@medj I've added [Troubleshooting](https://phalcon-compose.readme.io/docs/troubleshooting) section. So I think you have to pull latest images (in general `phalconphp/php-apache:ubuntu-16.04`) and recreate application containers. Also I've removed hardcoded container names in `docker-compose.yml` so you can have cache issue. Could you please try [`v2.0.3`](https://github.com/sergeyklay/phalcon-compose/releases/tag/v2.0.3)

**Comment by medj** [comment]
I started a brand new project.

docker-compose.yml
Changed port 80 => 81
Changed port 3306 => 3307

Copied variables.env.example => variables.env
Changed the value of `XDEBUG_REMOTE_HOST` to the value given to me by `ipconfig getifaddr en0` which is `192.168.0.20`

Ran `docker-compose up`

The `xdebug.remote_host` value in phpinfo() is still `localhost`
I'm not sure why this value does not seem to change for me.

**Comment by sergeyklay** [comment]
@medj  Well, as you can see, I've introduced custom provisions
https://github.com/sergeyklay/phalcon-compose/blob/master/docker/app/Dockerfile#L17

Just add required bash with:
```
echo xdebug.remote_host="$XDEBUG_REMOTE_HOST" >> /opt/docker/etc/php/php.ini
```

In any case try to login (`make root`) and `cat /opt/docker/etc/php/php.in` for debugging purposes

**Comment by sergeyklay** [comment]
After start containers contents of my `/opt/docker/etc/php/php.ini` is
```
; placeholder
xdebug.remote_connect_back="0"
xdebug.remote_host="192.168.1.129"
xdebug.remote_port="9000"
```

**Comment by medj** [comment]
I've created a file called `xdebug.sh` in the `bin` folder with the following contents:
`echo xdebug.remote_host="$XDEBUG_REMOTE_HOST" >> /opt/docker/etc/php/php.ini`

I've restarted all containers with the following the following:
```
docker-compose stop
docker-compose rm --force
docker-compose build --no-cache
docker-compose up -d
```

I checked contents of the `php.ini` file and it doesn't seem that the line above was echoed into it.

**Comment by medj** [comment]
Sorry, I put the xdebug.sh in the wrong bin folder.
Now I do see the line in my php.ini file. However, it stills shows localhost in phpinfo().

Is there a simple way to restart the apache server within the container? I was trying `apachectl restart`

**Comment by sergeyklay** [comment]
```sh
docker-compose stop
docker-compose start
```

?

**Comment by medj** [comment]
I visited your Troubleshooting section and ran `make reset`. Not sure what it was but it seemed to fix the problem.

<img width="866" alt="screen shot 2016-10-09 at 2 19 05 pm" src="https://cloud.githubusercontent.com/assets/882534/19222641/90ff622a-8e2b-11e6-80b4-0cd457fa1dd5.png">

Debugging working successfully now!
<img width="831" alt="screen shot 2016-10-09 at 2 20 10 pm" src="https://cloud.githubusercontent.com/assets/882534/19222640/90fdc280-8e2b-11e6-83a6-cbbabdc717ad.png">

Thanks so much for your patience on all of this!

**Comment by medj** [comment]
This is just a bonus question (nice to have). I'm used to using debugging with this button in PHPStorm, instead of having to create a configuration. Is it all possible to use this button, or not in this case?

<img width="51" alt="screen shot 2016-10-09 at 2 22 03 pm" src="https://cloud.githubusercontent.com/assets/882534/19222652/d03da82a-8e2b-11e6-9422-e23933ff8dea.png">

**Comment by sergeyklay** [comment]
Good question :)
I always use *Debug* button
![dbg-6](https://cloud.githubusercontent.com/assets/1256298/19222725/cab6b0b8-8e67-11e6-996a-8c7626818185.png)

So, issue can be closed?

**Comment by medj** [comment]
Yes, thank you!
